### ISSUE TITLE
clarification in atoms_index.txt

### ISSUE THREAD

**Issue by aswanthkrishna** [idocx/Atom2Vec#1]
the atoms_index.txt starts from 0. in the readme it is specified that this represents an atomic number. how should i interpret this?

**Comment by idocx** [comment]
It is the **internal index** stored in [`periodic_table.py`](https://github.com/idocx/Atom2Vec/blob/master/periodic_table.py#L1). As the material strings downloaded from `Materials Project` do not contain all the elements in the periodic table, we need to store all the element indexes in a file named [`atoms_index.txt`].

**Comment by idocx** [comment]
I ackownledge this is extremely confused. I will refactor the code recently with `pymatgen` package. The new version will be much more readable and all the unnecessary codes will be removed. There will not exist any `internal index` any more.

**Comment by aswanthkrishna** [comment]
I am assuming index n corresponds to atomic no n+1. am I correct? thanks for the quick reply!

**Comment by idocx** [comment]
> I am assuming index n corresponds to atomic no n+1. am I correct? thanks for the quick reply!

I think it is true :-)

**Comment by aswanthkrishna** [comment]
thanks a lot!
